name: MLOps Pipeline CI/CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_suite:
    runs-on: ubuntu-latest
    name: Run Test Suite
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run pytest
      run: |
        cd src && python -m pytest ../tests/ -v --tb=short
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: tests/

  train_and_quantize:
    runs-on: ubuntu-latest
    name: Train Model and Quantize
    needs: test_suite
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create models directory
      run: mkdir -p models
    
    - name: Train model
      run: cd src && python train.py
    
    - name: Perform quantization
      run: cd src && python quantize.py
    
    - name: Upload model artifacts
      uses: actions/upload-artifact@v4
      with:
        name: trained-models
        path: models/

  build_and_test_container:
    runs-on: ubuntu-latest
    name: Build and Test Docker Container
    needs: train_and_quantize
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Download model artifacts
      uses: actions/download-artifact@v4
      with:
        name: trained-models
        path: models/
    
    - name: Build Docker image
      run: docker build -t mlops-linear-regression .
    
    - name: Test Docker container execution
      run: docker run --rm mlops-linear-regression
    
    - name: Verify predict.py execution
      run: docker run --rm mlops-linear-regression python src/predict.py